using System;
using System.Collections.Generic;
using System.Linq;

namespace HousingNpcPose;

public enum PoseCategory
{
    Core,
    Gesture,
    Dance,
    Exercise,
    Performance,
    Prop,
    Experimental,
    Unknown,
}

public enum PoseSafety
{
    Safe,
    NeedsYOffset,
    NeedsFurniture,
    Experimental,
    GlitchyOrRestricted,
}

public enum PoseConfidence
{
    Confirmed,
    Likely,
    Uncertain,
    Experimental,
    ReferenceOnly,
}

public sealed record PoseDefinition(
    byte Param,
    string Key,
    string DisplayName,
    PoseCategory Category,
    PoseSafety Safety,
    PoseConfidence Confidence,
    string[] Aliases,
    string? ObservedAs = null,
    string? CsvSection = null,
    int? CsvRow = null,
    int? CsvOrdinal = null,
    string? CsvName = null,
    ushort? CsvId = null,
    ushort? CsvEmoteStart = null,
    ushort? ActionTimelineId = null,
    string? ActionTimelineKey = null,
    string? Notes = null)
{
    public string ParamText => $"{DisplayName} ({Param})";

    public string ObservedText => string.IsNullOrWhiteSpace(ObservedAs) ? DisplayName : ObservedAs;

    public string CsvText
    {
        get
        {
            var parts = new List<string>();

            if (!string.IsNullOrWhiteSpace(CsvSection))
                parts.Add(CsvSection);

            if (CsvOrdinal is { } ordinal)
                parts.Add($"#{ordinal}");

            if (!string.IsNullOrWhiteSpace(CsvName))
                parts.Add(CsvName);

            if (CsvId is { } csvId)
                parts.Add($"ID {csvId}");

            if (CsvEmoteStart is { } start)
                parts.Add($"start {start}");

            if (ActionTimelineId is { } timelineId && timelineId != CsvId)
                parts.Add($"timeline {timelineId}");

            if (!string.IsNullOrWhiteSpace(ActionTimelineKey))
                parts.Add(ActionTimelineKey);

            return parts.Count == 0 ? "-" : string.Join(" / ", parts);
        }
    }

    public string CsvRowText => CsvRow is { } row ? row.ToString() : "-";
}

public static class PoseCatalogue
{
    // Important: HousingNpcPose params are the small CharacterMode/ModeParam values proven in live testing.
    // The CSV fields below are crosswalk/reference metadata only. They are not a direct param formula.
    // User testing on housing NPCs showed useful InPositionLoop values clustered in roughly 1-100;
    // 101-255 currently appear to have no visible effect for this workflow.
    public static readonly IReadOnlyList<PoseDefinition> All = new List<PoseDefinition>
    {
        new(
            Param: 1,
            Key: "sit",
            DisplayName: "Sit / ground sit",
            Category: PoseCategory.Core,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "sit", "groundsit", "ground", "floor" },
            ObservedAs: "/sit",
            CsvSection: "Special",
            CsvRow: 194,
            CsvOrdinal: 68,
            CsvName: "Sit on Ground",
            CsvId: 654,
            CsvEmoteStart: 653,
            Notes: "ground sit"),
        new(
            Param: 2,
            Key: "chair",
            DisplayName: "Chair / bench sit",
            Category: PoseCategory.Core,
            Safety: PoseSafety.NeedsYOffset,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "chair", "bench", "chairsit", "sitbench", "seated", "sit" },
            ObservedAs: "/sit",
            CsvSection: "Special",
            CsvRow: 193,
            CsvOrdinal: 67,
            CsvName: "Sit",
            CsvId: 643,
            CsvEmoteStart: 642,
            Notes: "chairsit"),
        new(
            Param: 3,
            Key: "doze",
            DisplayName: "Doze / bed lie",
            Category: PoseCategory.Core,
            Safety: PoseSafety.NeedsFurniture,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "doze", "dozebedlie" },
            ObservedAs: "/doze",
            CsvSection: "General",
            CsvRow: 91,
            CsvName: "Doze",
            CsvId: 703),
        new(
            Param: 4,
            Key: "stepdance",
            DisplayName: "Step Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "stepdance" },
            ObservedAs: "/stepdance",
            CsvSection: "Special",
            CsvRow: 127,
            CsvOrdinal: 1,
            CsvName: "Step Dance",
            CsvId: 570,
            CsvEmoteStart: 569),
        new(
            Param: 5,
            Key: "harvestdance",
            DisplayName: "Harvest Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "harvestdance" },
            ObservedAs: "/harvestdance",
            CsvSection: "Special",
            CsvRow: 128,
            CsvOrdinal: 2,
            CsvName: "Harvest Dance",
            CsvId: 572,
            CsvEmoteStart: 571),
        new(
            Param: 6,
            Key: "balldance",
            DisplayName: "Ball Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "balldance" },
            ObservedAs: "/balldance",
            CsvSection: "Special",
            CsvRow: 129,
            CsvOrdinal: 3,
            CsvName: "Ball Dance",
            CsvId: 574,
            CsvEmoteStart: 573),
        new(
            Param: 7,
            Key: "mandervilledance",
            DisplayName: "Manderville Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "mandervilledance" },
            ObservedAs: "/mandervilledance",
            CsvSection: "Special",
            CsvRow: 130,
            CsvOrdinal: 4,
            CsvName: "Manderville Dance",
            CsvId: 576,
            CsvEmoteStart: 575),
        new(
            Param: 8,
            Key: "bombdance",
            DisplayName: "Bomb Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "bombdance" },
            ObservedAs: "/bombdance",
            CsvSection: "Special",
            CsvRow: 131,
            CsvOrdinal: 5,
            CsvName: "Bomb Dance",
            CsvId: 3188,
            CsvEmoteStart: 3187),
        new(
            Param: 9,
            Key: "hildypose",
            DisplayName: "Hildy (Pose)",
            Category: PoseCategory.Unknown,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "hildypose", "poseonly" },
            ObservedAs: "/hildy (POSE)",
            CsvSection: "Special",
            CsvRow: 132,
            CsvOrdinal: 6,
            CsvName: "Most Gentlemanly",
            CsvId: 3764,
            CsvEmoteStart: 3763,
            ActionTimelineId: 1026,
            ActionTimelineKey: "event_base/event_base_hildi_pose",
            Notes: "pose only"),
        new(
            Param: 10,
            Key: "thavdance",
            DisplayName: "Thavnairian Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "thavdance", "thavnairiandance" },
            ObservedAs: "/thavdance",
            CsvSection: "Special",
            CsvRow: 133,
            CsvOrdinal: 7,
            CsvName: "Thavnairian Dance",
            CsvId: 3775,
            CsvEmoteStart: 3774),
        new(
            Param: 11,
            Key: "golddance",
            DisplayName: "Gold Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "golddance" },
            ObservedAs: "/golddance",
            CsvSection: "Special",
            CsvRow: 134,
            CsvOrdinal: 8,
            CsvName: "Gold Dance",
            CsvId: 3777,
            CsvEmoteStart: 3776),
        new(
            Param: 12,
            Key: "sundance",
            DisplayName: "Sundrop Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "sundance", "sundropdance" },
            ObservedAs: "/sundance",
            CsvSection: "Special",
            CsvRow: 135,
            CsvOrdinal: 9,
            CsvName: "Sundrop Dance",
            CsvId: 3773,
            CsvEmoteStart: 3772),
        new(
            Param: 13,
            Key: "moonlift",
            DisplayName: "Moonlift Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "moonlift", "moonliftdance" },
            ObservedAs: "/moonlift",
            CsvSection: "Special",
            CsvRow: 136,
            CsvOrdinal: 10,
            CsvName: "Moonlift Dance",
            CsvId: 4810,
            CsvEmoteStart: 4809),
        new(
            Param: 14,
            Key: "mogdance",
            DisplayName: "Moogle Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "mogdance", "moogledance" },
            ObservedAs: "/mogdance",
            CsvSection: "Special",
            CsvRow: 137,
            CsvOrdinal: 11,
            CsvName: "Moogle Dance",
            CsvId: 4673,
            CsvEmoteStart: 4672),
        new(
            Param: 15,
            Key: "redrangerposea",
            DisplayName: "Red Ranger Pose A",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "redrangerposea", "inpositionloop15" },
            ObservedAs: "InPositionLoop 15",
            CsvSection: "Special",
            CsvRow: 138,
            CsvOrdinal: 12,
            CsvName: "Red Ranger Pose A",
            CsvId: 4785,
            CsvEmoteStart: 4784,
            Notes: "Red Ranger Pose A"),
        new(
            Param: 16,
            Key: "redrangerposeb",
            DisplayName: "Red Ranger Pose B",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "redrangerposeb", "inpositionloop16" },
            ObservedAs: "InPositionLoop 16",
            CsvSection: "Special",
            CsvRow: 139,
            CsvOrdinal: 13,
            CsvName: "Red Ranger Pose B",
            CsvId: 4793,
            CsvEmoteStart: 4792,
            Notes: "Red Ranger Pose B"),
        new(
            Param: 17,
            Key: "blackrangerposea",
            DisplayName: "Black Ranger Pose A",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "blackrangerposea", "inpositionloop17" },
            ObservedAs: "InPositionLoop 17",
            CsvSection: "Special",
            CsvRow: 140,
            CsvOrdinal: 14,
            CsvName: "Black Ranger Pose A",
            CsvId: 4789,
            CsvEmoteStart: 4788,
            Notes: "Black Ranger Pose A"),
        new(
            Param: 18,
            Key: "blackrangerposeb",
            DisplayName: "Black Ranger Pose B",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "blackrangerposeb", "inpositionloop18" },
            ObservedAs: "InPositionLoop 18",
            CsvSection: "Special",
            CsvRow: 141,
            CsvOrdinal: 15,
            CsvName: "Black Ranger Pose B",
            CsvId: 4797,
            CsvEmoteStart: 4796,
            Notes: "Black Ranger Pose B"),
        new(
            Param: 19,
            Key: "yellowrangerposea",
            DisplayName: "Yellow Ranger Pose A",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "yellowrangerposea", "inpositionloop19" },
            ObservedAs: "InPositionLoop 19",
            CsvSection: "Special",
            CsvRow: 142,
            CsvOrdinal: 16,
            CsvName: "Yellow Ranger Pose A",
            CsvId: 4787,
            CsvEmoteStart: 4786,
            Notes: "Yellow Ranger Pose A"),
        new(
            Param: 20,
            Key: "yellowrangerposeb",
            DisplayName: "Yellow Ranger Pose B",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "yellowrangerposeb", "inpositionloop20" },
            ObservedAs: "InPositionLoop 20",
            CsvSection: "Special",
            CsvRow: 143,
            CsvOrdinal: 17,
            CsvName: "Yellow Ranger Pose B",
            CsvId: 4795,
            CsvEmoteStart: 4794,
            Notes: "Yellow Ranger Pose B"),
        new(
            Param: 21,
            Key: "playdead",
            DisplayName: "Play Dead",
            Category: PoseCategory.Experimental,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "playdead" },
            ObservedAs: "/playdead",
            CsvSection: "Special",
            CsvRow: 179,
            CsvOrdinal: 53,
            CsvName: "Play Dead",
            CsvId: 4799,
            CsvEmoteStart: 4798),
        new(
            Param: 22,
            Key: "easterndance",
            DisplayName: "Eastern Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "easterndance" },
            ObservedAs: "/easterndance",
            CsvSection: "Special",
            CsvRow: 144,
            CsvOrdinal: 18,
            CsvName: "Eastern Dance",
            CsvId: 4783,
            CsvEmoteStart: 4782),
        new(
            Param: 23,
            Key: "songbird",
            DisplayName: "Songbird",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "songbird" },
            ObservedAs: "/songbird",
            CsvSection: "Special",
            CsvRow: 145,
            CsvOrdinal: 19,
            CsvName: "Songbird",
            CsvId: 4818,
            CsvEmoteStart: 4817),
        new(
            Param: 24,
            Key: "standingpose",
            DisplayName: "Standing pose",
            Category: PoseCategory.Unknown,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "standingpose", "inpositionloop24" },
            ObservedAs: "InPositionLoop 24",
            Notes: "Standing Pose"),
        new(
            Param: 25,
            Key: "squats",
            DisplayName: "Squats",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "squats" },
            ObservedAs: "/squats",
            CsvSection: "Special",
            CsvRow: 165,
            CsvOrdinal: 39,
            CsvName: "Squats",
            CsvId: 5803,
            CsvEmoteStart: 5812),
        new(
            Param: 26,
            Key: "pushups",
            DisplayName: "Push-ups",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "pushups" },
            ObservedAs: "/pushups",
            CsvSection: "Special",
            CsvRow: 166,
            CsvOrdinal: 40,
            CsvName: "Push-ups",
            CsvId: 5800,
            CsvEmoteStart: 5799),
        new(
            Param: 27,
            Key: "situps",
            DisplayName: "Sit-ups",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "situps" },
            ObservedAs: "/situps",
            CsvSection: "Special",
            CsvRow: 167,
            CsvOrdinal: 41,
            CsvName: "Sit-ups",
            CsvId: 5802,
            CsvEmoteStart: 5801),
        new(
            Param: 28,
            Key: "breathcontrol",
            DisplayName: "Breath Control",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "breathcontrol" },
            ObservedAs: "/breathcontrol",
            CsvSection: "Special",
            CsvRow: 168,
            CsvOrdinal: 42,
            CsvName: "Breath Control",
            CsvId: 5804,
            CsvEmoteStart: 5813),
        new(
            Param: 29,
            Key: "attention",
            DisplayName: "Attention",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "attention" },
            ObservedAs: "/attention",
            CsvSection: "Special",
            CsvRow: 169,
            CsvOrdinal: 43,
            CsvName: "Attention",
            CsvId: 5806,
            CsvEmoteStart: 5805),
        new(
            Param: 30,
            Key: "atease",
            DisplayName: "At Ease",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "atease" },
            ObservedAs: "/atease",
            CsvSection: "Special",
            CsvRow: 170,
            CsvOrdinal: 44,
            CsvName: "At Ease",
            CsvId: 5808,
            CsvEmoteStart: 5807),
        new(
            Param: 31,
            Key: "box",
            DisplayName: "Box",
            Category: PoseCategory.Exercise,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "box" },
            ObservedAs: "/box",
            CsvSection: "Special",
            CsvRow: 171,
            CsvOrdinal: 45,
            CsvName: "Box",
            CsvId: 5809,
            CsvEmoteStart: 5814),
        new(
            Param: 32,
            Key: "ritualprayer",
            DisplayName: "Ritual Prayer",
            Category: PoseCategory.Unknown,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "ritualprayer" },
            ObservedAs: "/ritualprayer",
            CsvSection: "Special",
            CsvRow: 146,
            CsvOrdinal: 20,
            CsvName: "Ritual Prayer",
            CsvId: 6219,
            CsvEmoteStart: 6218),
        new(
            Param: 33,
            Key: "charmed",
            DisplayName: "Charmed",
            Category: PoseCategory.Unknown,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "charmed" },
            ObservedAs: "/charmed",
            CsvSection: "Special",
            CsvRow: 147,
            CsvOrdinal: 21,
            CsvName: "Charmed",
            CsvId: 6242,
            CsvEmoteStart: 6241),
        new(
            Param: 34,
            Key: "cheerlightblue",
            DisplayName: "Cheer Light Blue",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerlightblue" },
            ObservedAs: "/cheerlightblue",
            CsvSection: "Special",
            CsvRow: 148,
            CsvOrdinal: 22,
            CsvName: "Cheer On",
            CsvId: 6244,
            CsvEmoteStart: 6243),
        new(
            Param: 35,
            Key: "cheerlightyellow",
            DisplayName: "Cheer Light Yellow",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerlightyellow" },
            ObservedAs: "/cheerlightyellow",
            CsvSection: "Special",
            CsvRow: 149,
            CsvOrdinal: 23,
            CsvName: "Cheer Wave",
            CsvId: 6246,
            CsvEmoteStart: 6245),
        new(
            Param: 36,
            Key: "cheerlightred",
            DisplayName: "Cheer Light Red",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerlightred" },
            ObservedAs: "/cheerlightred",
            CsvSection: "Special",
            CsvRow: 150,
            CsvOrdinal: 24,
            CsvName: "Cheer Jump",
            CsvId: 6248,
            CsvEmoteStart: 6247),
        new(
            Param: 37,
            Key: "tremble",
            DisplayName: "Tremble",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "tremble" },
            ObservedAs: "/tremble",
            CsvSection: "Special",
            CsvRow: 174,
            CsvOrdinal: 48,
            CsvName: "Tremble",
            CsvId: 6233,
            CsvEmoteStart: 6232),
        new(
            Param: 38,
            Key: "winded",
            DisplayName: "Winded",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "winded" },
            ObservedAs: "/winded",
            CsvSection: "Special",
            CsvRow: 175,
            CsvOrdinal: 49,
            CsvName: "Winded",
            CsvId: 6235,
            CsvEmoteStart: 6234),
        new(
            Param: 39,
            Key: "boxstep",
            DisplayName: "Box step?",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "boxstep", "inpositionloop39" },
            ObservedAs: "InPositionLoop 39",
            CsvSection: "Special",
            CsvRow: 152,
            CsvOrdinal: 26,
            CsvName: "Box Step",
            CsvId: 6258,
            CsvEmoteStart: 6257,
            Notes: "box step?"),
        new(
            Param: 40,
            Key: "sidestep",
            DisplayName: "Side step?",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "sidestep", "inpositionloop40" },
            ObservedAs: "InPositionLoop 40",
            CsvSection: "Special",
            CsvRow: 153,
            CsvOrdinal: 27,
            CsvName: "Side Step",
            CsvId: 6260,
            CsvEmoteStart: 6259,
            Notes: "side step?"),
        new(
            Param: 41,
            Key: "yoldance",
            DisplayName: "Yol Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "yoldance" },
            ObservedAs: "/yoldance",
            CsvSection: "Special",
            CsvRow: 151,
            CsvOrdinal: 25,
            CsvName: "Yol Dance",
            CsvId: 6231,
            CsvEmoteStart: 6230),
        new(
            Param: 42,
            Key: "sweat",
            DisplayName: "Sweat",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "sweat" },
            ObservedAs: "/sweat",
            CsvSection: "Special",
            CsvRow: 172,
            CsvOrdinal: 46,
            CsvName: "Sweat",
            CsvId: 6237,
            CsvEmoteStart: 6236),
        new(
            Param: 43,
            Key: "shiver",
            DisplayName: "Shiver",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "shiver" },
            ObservedAs: "/shiver",
            CsvSection: "Special",
            CsvRow: 173,
            CsvOrdinal: 47,
            CsvName: "Shiver",
            CsvId: 6239,
            CsvEmoteStart: 6238),
        new(
            Param: 44,
            Key: "sidestep44",
            DisplayName: "Side Step?",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "sidestep44", "sidestep", "inpositionloop44" },
            ObservedAs: "InPositionLoop 44",
            Notes: "Side Step?"),
        new(
            Param: 45,
            Key: "getfantasy",
            DisplayName: "Get Fantasy?",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "getfantasy", "inpositionloop45" },
            ObservedAs: "InPositionLoop 45",
            CsvSection: "Special",
            CsvRow: 154,
            CsvOrdinal: 28,
            CsvName: "Get Fantasy",
            CsvId: 6294,
            CsvEmoteStart: 6293,
            Notes: "Get Fantasy?"),
        new(
            Param: 46,
            Key: "popotostep",
            DisplayName: "Popoto Step?",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "popotostep", "inpositionloop46" },
            ObservedAs: "InPositionLoop 46",
            CsvSection: "Special",
            CsvRow: 155,
            CsvOrdinal: 29,
            CsvName: "Popoto Step",
            CsvId: 6296,
            CsvEmoteStart: 6295,
            Notes: "Popoto Step?"),
        new(
            Param: 47,
            Key: "confirm",
            DisplayName: "Confirm",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "confirm", "knownusefulgesture" },
            ObservedAs: "/confirm",
            CsvSection: "Special",
            CsvRow: 176,
            CsvOrdinal: 50,
            CsvName: "Confirm",
            CsvId: 6273,
            CsvEmoteStart: 6272,
            Notes: "known useful gesture"),
        new(
            Param: 48,
            Key: "scheme",
            DisplayName: "Scheme",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "scheme", "knownusefulgesture" },
            ObservedAs: "/scheme",
            CsvSection: "Special",
            CsvRow: 177,
            CsvOrdinal: 51,
            CsvName: "Scheme",
            CsvId: 6275,
            CsvEmoteStart: 6274,
            Notes: "known useful gesture"),
        new(
            Param: 49,
            Key: "danceunclear",
            DisplayName: "Dance / unclear",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "danceunclear", "inpositionloop49" },
            ObservedAs: "InPositionLoop 49",
            Notes: "dance / unclear"),
        new(
            Param: 50,
            Key: "stepdancelikevariant",
            DisplayName: "Stepdance-like variant",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "stepdancelikevariant", "inpositionloop50" },
            ObservedAs: "InPositionLoop 50",
            Notes: "stepdance-like variant"),
        new(
            Param: 51,
            Key: "reprimand",
            DisplayName: "Reprimand",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "reprimand", "knownusefulgesture" },
            ObservedAs: "/reprimand",
            CsvSection: "Special",
            CsvRow: 178,
            CsvOrdinal: 52,
            CsvName: "Reprimand",
            CsvId: 6277,
            CsvEmoteStart: 6276,
            Notes: "known useful gesture"),
        new(
            Param: 52,
            Key: "mandervillemambo",
            DisplayName: "Manderville Mambo",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "mandervillemambo" },
            ObservedAs: "/mandervillemambo",
            CsvSection: "Special",
            CsvRow: 159,
            CsvOrdinal: 33,
            CsvName: "Manderville Mambo",
            CsvId: 6305,
            CsvEmoteStart: 6304),
        new(
            Param: 53,
            Key: "simulationm",
            DisplayName: "Simulation M",
            Category: PoseCategory.Experimental,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "simulationm", "inpositionloop53" },
            ObservedAs: "InPositionLoop 53",
            CsvSection: "Special",
            CsvRow: 191,
            CsvOrdinal: 65,
            CsvName: "Simulation M",
            CsvId: 6307,
            CsvEmoteStart: 6306,
            Notes: "Simulation M"),
        new(
            Param: 54,
            Key: "simulationf",
            DisplayName: "Simulation F",
            Category: PoseCategory.Experimental,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "simulationf", "inpositionloop54" },
            ObservedAs: "InPositionLoop 54",
            CsvSection: "Special",
            CsvRow: 192,
            CsvOrdinal: 66,
            CsvName: "Simulation F",
            CsvId: 6309,
            CsvEmoteStart: 6308,
            Notes: "Simulation F"),
        new(
            Param: 55,
            Key: "lean",
            DisplayName: "Lean",
            Category: PoseCategory.Core,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "lean" },
            ObservedAs: "/lean",
            CsvSection: "Special",
            CsvRow: 180,
            CsvOrdinal: 54,
            CsvName: "Lean",
            CsvId: 6280,
            CsvEmoteStart: 6279),
        new(
            Param: 56,
            Key: "wasshoi",
            DisplayName: "Wasshoi",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "wasshoi" },
            ObservedAs: "/wasshoi",
            CsvSection: "Special",
            CsvRow: 160,
            CsvOrdinal: 34,
            CsvName: "Wasshoi",
            CsvId: 7389,
            CsvEmoteStart: 7388,
            ActionTimelineKey: "event/event_wa_syoi"),
        new(
            Param: 57,
            Key: "flamedance",
            DisplayName: "Flame Dance",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "flamedance" },
            ObservedAs: "/flamedance",
            CsvSection: "Special",
            CsvRow: 161,
            CsvOrdinal: 35,
            CsvName: "Flame Dance",
            CsvId: 7409,
            CsvEmoteStart: 7408),
        new(
            Param: 58,
            Key: "guard",
            DisplayName: "Guard",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "guard" },
            ObservedAs: "/guard",
            CsvSection: "Special",
            CsvRow: 181,
            CsvOrdinal: 55,
            CsvName: "Guard",
            CsvId: 7401,
            CsvEmoteStart: 7400),
        new(
            Param: 59,
            Key: "malevolence",
            DisplayName: "Malevolence",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "malevolence" },
            ObservedAs: "/malevolence",
            CsvSection: "Special",
            CsvRow: 182,
            CsvOrdinal: 56,
            CsvName: "Malevolence",
            CsvId: 7403,
            CsvEmoteStart: 7402),
        new(
            Param: 60,
            Key: "beesknees",
            DisplayName: "Bee's Knees",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "beesknees" },
            ObservedAs: "/beesknees",
            CsvSection: "Special",
            CsvRow: 162,
            CsvOrdinal: 36,
            CsvName: "Bee's Knees",
            CsvId: 7392,
            CsvEmoteStart: 7391),
        new(
            Param: 61,
            Key: "lalihop",
            DisplayName: "Lali-hop",
            Category: PoseCategory.Dance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "lalihop" },
            ObservedAs: "/lalihop",
            CsvSection: "Special",
            CsvRow: 163,
            CsvOrdinal: 37,
            CsvName: "Lali Hop",
            CsvId: 7419,
            CsvEmoteStart: 7418),
        new(
            Param: 62,
            Key: "wringhands",
            DisplayName: "Wring Hands",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "wringhands" },
            ObservedAs: "/wringhands",
            CsvSection: "Special",
            CsvRow: 183,
            CsvOrdinal: 57,
            CsvName: "Wring Hands",
            CsvId: 7396,
            CsvEmoteStart: 7395),
        new(
            Param: 63,
            Key: "sweep",
            DisplayName: "Sweep Up",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "sweep", "sweepup" },
            ObservedAs: "/sweep",
            CsvSection: "Special",
            CsvRow: 184,
            CsvOrdinal: 58,
            CsvName: "Sweep Up",
            CsvId: 8016,
            CsvEmoteStart: 8015),
        new(
            Param: 64,
            Key: "showright",
            DisplayName: "Show Right",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "showright" },
            ObservedAs: "/showright",
            CsvSection: "Special",
            CsvRow: 185,
            CsvOrdinal: 59,
            CsvName: "Show Right",
            CsvId: 8070,
            CsvEmoteStart: 8069),
        new(
            Param: 65,
            Key: "showleft",
            DisplayName: "Show Left",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "showleft" },
            ObservedAs: "/showleft",
            CsvSection: "Special",
            CsvRow: 186,
            CsvOrdinal: 60,
            CsvName: "Show Left",
            CsvId: 8072,
            CsvEmoteStart: 8071),
        new(
            Param: 66,
            Key: "spirit",
            DisplayName: "Spirit",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "spirit" },
            ObservedAs: "/spirit"),
        new(
            Param: 67,
            Key: "cheerrythmnbright",
            DisplayName: "Cheery Rhythm Bright",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerrythmnbright", "cheeryrhythmbright" },
            ObservedAs: "/cheerrythmnbright"),
        new(
            Param: 68,
            Key: "cheerrythmnviolet",
            DisplayName: "Cheery Rhythm Violet",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerrythmnviolet", "cheeryrhythmviolet" },
            ObservedAs: "/cheerrythmnviolet"),
        new(
            Param: 69,
            Key: "cheerlightgreen",
            DisplayName: "Cheer Light Green",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerlightgreen" },
            ObservedAs: "/cheerlightgreen"),
        new(
            Param: 70,
            Key: "param70novisibleresult",
            DisplayName: "Param 70 / no visible result",
            Category: PoseCategory.Experimental,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "param70novisibleresult", "novisibleresultunverified", "missingfromfirstpass" },
            ObservedAs: "No visible result / unverified",
            Notes: "No reliable visible result in first 1-100 pass; leave as unknown until retested."),
        new(
            Param: 71,
            Key: "slump",
            DisplayName: "Slump",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "slump" },
            ObservedAs: "/slump"),
        new(
            Param: 72,
            Key: "loveheart",
            DisplayName: "Love Heart",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "loveheart" },
            ObservedAs: "/loveheart"),
        new(
            Param: 73,
            Key: "zantetsuken",
            DisplayName: "Zantetsuken",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Likely,
            Aliases: new[] { "zantetsuken", "inpositionloop73" },
            ObservedAs: "InPositionLoop 73",
            CsvSection: "Special",
            CsvRow: 187,
            CsvOrdinal: 61,
            CsvName: "Zantetsuken",
            CsvId: 4803,
            Notes: "Zantetsuken"),
        new(
            Param: 74,
            Key: "diamonddustrestrictedslot",
            DisplayName: "Diamond Dust / restricted slot",
            Category: PoseCategory.Experimental,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "diamonddustrestrictedslot", "novisibleresultlikelypaidrestricted", "possiblydiamonddustpaidrestrictedslot" },
            ObservedAs: "No visible result / likely paid/restricted",
            CsvSection: "Special",
            CsvRow: 188,
            CsvOrdinal: 62,
            CsvName: "Diamond Dust",
            CsvId: 4802,
            Notes: "Likely paid/restricted slot; no reliable live verification yet."),
        new(
            Param: 75,
            Key: "water",
            DisplayName: "Water Float",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "water", "waterfloat" },
            ObservedAs: "/water",
            CsvSection: "Special",
            CsvRow: 164,
            CsvOrdinal: 38,
            CsvName: "Water Float",
            CsvId: 4807,
            CsvEmoteStart: 4806),
        new(
            Param: 76,
            Key: "mixingdrinks",
            DisplayName: "Mixing drinks?",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "mixingdrinks", "inpositionloop76" },
            ObservedAs: "InPositionLoop 76",
            Notes: "mixing drinks?"),
        new(
            Param: 77,
            Key: "givingflowers",
            DisplayName: "Giving flowers?",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "givingflowers", "inpositionloop77" },
            ObservedAs: "InPositionLoop 77",
            Notes: "giving flowers?"),
        new(
            Param: 78,
            Key: "givingflowerslow",
            DisplayName: "Giving flowers? low",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "givingflowerslow", "inpositionloop78" },
            ObservedAs: "InPositionLoop 78",
            Notes: "giving flowers? low"),
        new(
            Param: 79,
            Key: "dazed",
            DisplayName: "Dazed",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "dazed" },
            ObservedAs: "/dazed"),
        new(
            Param: 80,
            Key: "rage",
            DisplayName: "Rage",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "rage" },
            ObservedAs: "/rage"),
        new(
            Param: 81,
            Key: "tomescroll",
            DisplayName: "Tomestone Scroll",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "tomescroll", "tomestonescroll" },
            ObservedAs: "/tomescroll",
            CsvSection: "General",
            CsvRow: 108,
            CsvName: "Tomestone",
            CsvId: 6302),
        new(
            Param: 82,
            Key: "study",
            DisplayName: "Study",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "study" },
            ObservedAs: "/study"),
        new(
            Param: 83,
            Key: "savortea",
            DisplayName: "Savor Tea",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "savortea" },
            ObservedAs: "/savortea",
            CsvSection: "General",
            CsvRow: 115,
            CsvName: "Drink Tea",
            CsvId: 8058),
        new(
            Param: 84,
            Key: "lominsangulp",
            DisplayName: "Lominsan Gulp",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "lominsangulp" },
            ObservedAs: "/lominsangulp"),
        new(
            Param: 85,
            Key: "gridaniangulp",
            DisplayName: "Gridanian Gulp",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "gridaniangulp" },
            ObservedAs: "/gridaniangulp"),
        new(
            Param: 86,
            Key: "uldahngulp",
            DisplayName: "Ul'dahn Gulp",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "uldahngulp" },
            ObservedAs: "/uldahngulp"),
        new(
            Param: 87,
            Key: "writingwithafeather",
            DisplayName: "Writing with a feather?",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "writingwithafeather", "inpositionloop87" },
            ObservedAs: "InPositionLoop 87",
            Notes: "writing with a feather?"),
        new(
            Param: 88,
            Key: "cheerrythmnred",
            DisplayName: "Cheery Rhythm Red",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerrythmnred", "cheeryrhythmred" },
            ObservedAs: "/cheerrythmnred"),
        new(
            Param: 89,
            Key: "cheerlightyellow89",
            DisplayName: "Cheer Light Yellow",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerlightyellow89", "cheerlightyellow" },
            ObservedAs: "/cheerlightyellow"),
        new(
            Param: 90,
            Key: "maraccas",
            DisplayName: "Maraccas?",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "maraccas", "inpositionloop90" },
            ObservedAs: "InPositionLoop 90",
            Notes: "maraccas?"),
        new(
            Param: 91,
            Key: "maraccas91",
            DisplayName: "Maraccas?",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "maraccas91", "maraccas", "inpositionloop91" },
            ObservedAs: "InPositionLoop 91",
            Notes: "maraccas?"),
        new(
            Param: 92,
            Key: "maraccas92",
            DisplayName: "Maraccas?",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "maraccas92", "maraccas", "inpositionloop92" },
            ObservedAs: "InPositionLoop 92",
            Notes: "maraccas?"),
        new(
            Param: 93,
            Key: "holdingabook",
            DisplayName: "Holding a book",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Experimental,
            Confidence: PoseConfidence.Uncertain,
            Aliases: new[] { "holdingabook", "inpositionloop93" },
            ObservedAs: "InPositionLoop 93",
            Notes: "holding a book"),
        new(
            Param: 94,
            Key: "cheerythmnviolet",
            DisplayName: "Cheery Rhythm Violet",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerythmnviolet", "cheeryrhythmviolet" },
            ObservedAs: "/cheerythmnviolet"),
        new(
            Param: 95,
            Key: "cheerythmnbright",
            DisplayName: "Cheery Rhythm Bright",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerythmnbright", "cheeryrhythmbright" },
            ObservedAs: "/cheerythmnbright"),
        new(
            Param: 96,
            Key: "cheerythmnbright96",
            DisplayName: "Cheery Rhythm Bright",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerythmnbright96", "cheeryrhythmbright", "cheerythmnbright" },
            ObservedAs: "/cheerythmnbright"),
        new(
            Param: 97,
            Key: "cheerlightgreen97",
            DisplayName: "Cheer Light Green",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cheerlightgreen97", "cheerlightgreen" },
            ObservedAs: "/cheerlightgreen"),
        new(
            Param: 98,
            Key: "cackle",
            DisplayName: "Cackle",
            Category: PoseCategory.Gesture,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "cackle" },
            ObservedAs: "/cackle"),
        new(
            Param: 99,
            Key: "conduct",
            DisplayName: "Conduct",
            Category: PoseCategory.Performance,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "conduct" },
            ObservedAs: "/conduct"),
        new(
            Param: 100,
            Key: "eattaco",
            DisplayName: "Eat Taco",
            Category: PoseCategory.Prop,
            Safety: PoseSafety.Safe,
            Confidence: PoseConfidence.Confirmed,
            Aliases: new[] { "eattaco" },
            ObservedAs: "/eattaco"),
    };

    public static IEnumerable<PoseDefinition> ByCategory(PoseCategory category)
        => All.Where(definition => definition.Category == category).OrderBy(definition => definition.Param);

    public static bool TryGetByAlias(string alias, out PoseDefinition definition)
    {
        var normalized = NormalizeAlias(alias);
        definition = All.FirstOrDefault(candidate =>
            string.Equals(candidate.Key, normalized, StringComparison.OrdinalIgnoreCase) ||
            candidate.Aliases.Any(candidateAlias => string.Equals(NormalizeAlias(candidateAlias), normalized, StringComparison.OrdinalIgnoreCase)))!;

        return definition != null;
    }

    public static bool TryGetByParam(byte param, out PoseDefinition definition)
    {
        definition = All.FirstOrDefault(candidate => candidate.Param == param)!;
        return definition != null;
    }

    public static string GetDisplayName(byte param)
    {
        return TryGetByParam(param, out var definition) ? definition.DisplayName : $"Custom Pos {param}";
    }

    public static string GetLabel(byte param, string prefix)
    {
        return TryGetByParam(param, out var definition) ? $"{prefix} {param}: {definition.DisplayName}" : $"{prefix} {param}";
    }

    public static string GetSavedDisplayName(byte param, string storedLabel)
    {
        if (TryGetByParam(param, out var definition))
            return definition.DisplayName;

        return string.IsNullOrWhiteSpace(storedLabel) ? $"Custom Pos {param}" : storedLabel;
    }

    public static string KnownCommandNames()
    {
        return string.Join(", ", All
            .Where(definition => definition.Category != PoseCategory.Unknown)
            .Select(definition => definition.Key)
            .OrderBy(key => key, StringComparer.OrdinalIgnoreCase));
    }

    public static string NormalizeAlias(string alias)
    {
        return (alias ?? string.Empty)
            .Trim()
            .ToLowerInvariant()
            .Replace("_", string.Empty)
            .Replace("-", string.Empty)
            .Replace(" ", string.Empty)
            .Replace("/", string.Empty)
            .Replace("'", string.Empty)
            .Replace(".", string.Empty);
    }
}
